# Generated by Django 4.1.3 on 2022-12-03 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SaleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_y', models.DateField(blank=True, default=datetime.datetime.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='users.profile_user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('admin_madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_by', to='users.profile_admin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_in', to='products.category')),
                ('sale_lists', models.ManyToManyField(blank=True, related_name='sold_in', to='products.salelist')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_in', to='products.product_status')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_x', models.DateField(blank=True, default=datetime.date.today)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.profile_admin')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=1)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_price_list', to='products.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product', to='products.product')),
            ],
        ),
    ]
