# Generated by Django 4.1.3 on 2022-12-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_status',
            options={'verbose_name': 'Produst status', 'verbose_name_plural': 'Product status all'},
        ),
    ]
